kind: Deployment
apiVersion: apps/v1
metadata:
  name: cyl-shop-web
  namespace: cyl-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyl-shop-web
  template:
    metadata:
      labels:
        app: cyl-shop-web
      annotations:
        buildNumber: '$BUILD_NUMBER'
    spec:
      containers:
        - name: cyl-shop-web
          image: 'registry.cn-hangzhou.aliyuncs.com/cyl-dev/cyl-shop-web:1.0.0'
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Shanghai
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: ali-cyl-test
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
